#[allow(dead_code)]
pub enum Category {
    Internal,
    Connectors,
    Dataload,
    DataloadDownload,
    DataloadEventstore,
    DataloadMetadataStorage,
    DataloadProcesses,
    EventStores,
    Invitations,
    Ldm,
    Metadata,
    MetadataAnalyticDashboard,
    MetadataAttributes,
    MetadataColumns,
    MetadataDataLoadingColumns,
    MetadataDatasets,
    MetadataDateFilterSettings,
    MetadataDimensions,
    MetadataDomains,
    MetadataEtlFiles,
    MetadataExecutionContexts,
    MetadataFacts,
    MetadataFilters,
    MetadataFolders,
    MetadataKpi,
    MetadataKpiAlert,
    MetadataListAttributeFilter,
    MetadataMetrics,
    MetadataProjectDashboards,
    MetadataPrompts,
    MetadataReportDefinition,
    MetadataReports,
    MetadataSchedulEdmails,
    MetadataTableDataLoads,
    MetadataTables,
    MetadataUserFilters,
    MetadataVisualizations,
    PublicArtifacts,
    Roles,
    Schedules,
    Templates,
    Uploads,
    Users,
}

pub enum ReservedFile {
    Root = 0,
    FeatureFlagsJson = 2,
    PermissionsJson,
    ProjectJson,
    RolesJson,
}
